### ISSUE TITLE
Uncaught TypeError: this.buffer.getLanguageMode(...).bufferRangeForScopeAtPosition is not a function

### ISSUE THREAD

**Issue by dflock** [klorenz/atom-regex-railroad-diagrams#103]
[Enter steps to reproduce:]

1. Click a non-regex line of code in a Javascript file

**Atom**: 1.25.0-beta2 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.3
**Thrown From**: [regex-railroad-diagram](https://github.com/klorenz/atom-regex-railroad-diagrams) package 0.19.4

### Stack Trace

Uncaught TypeError: this.buffer.getLanguageMode(...).bufferRangeForScopeAtPosition is not a function

```
At /usr/share/atom-beta/resources/app/src/text-editor.js:3680

TypeError: this.buffer.getLanguageMode(...).bufferRangeForScopeAtPosition is not a function
    at TextEditor.bufferRangeForScopeAtPosition (/usr/share/atom-beta/resources/app/src/text-editor.js:3680:48)
    at TextEditor.bufferRangeForScopeAtCursor (/usr/share/atom-beta/resources/app/src/text-editor.js:3676:23)
    at Object.bufferRangeForScope (/packages/regex-railroad-diagram/lib/regex-railroad-diagram.coffee:87:25)
    at Object.getRegexpBufferRange (/packages/regex-railroad-diagram/lib/regex-railroad-diagram.coffee:133:14)
    at Object.checkForRegExp (/packages/regex-railroad-diagram/lib/regex-railroad-diagram.coffee:193:25)
    at /packages/regex-railroad-diagram/lib/regex-railroad-diagram.coffee:29:73
    at later (/packages/asciidoc-image-helper/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/underscore-plus/node_modules/underscore/underscore.js:724:25)
```

### Commands

```
     -0:41.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:41.1.0 docblockr:parse-enter (input.hidden-input)
     -0:41.1.0 editor:newline (input.hidden-input)
  5x -0:40.3.0 core:backspace (input.hidden-input)
     -0:38 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:37.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:37.9.0 docblockr:parse-enter (input.hidden-input)
     -0:37.9.0 editor:newline (input.hidden-input)
  3x -0:35.4.0 core:move-up (input.hidden-input)
  7x -0:34.8.0 core:move-right (input.hidden-input)
     -0:33.5.0 core:move-left (input.hidden-input)
     -0:33 intentions:highlight (input.hidden-input)
  3x -0:32.7.0 editor:select-to-end-of-word (input.hidden-input)
     -0:30.5.0 autocomplete-plus:cancel (input.hidden-input)
     -0:29.7.0 intentions:highlight (input.hidden-input)
     -0:29.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
ansible-snippets 0.2.0 
ariake-dark-syntax 0.1.3 
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.4 
atom-alignment 0.13.0 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.30.9 
atom-dark-fusion-syntax 2.2.1 
atom-jade 0.3.0 
atom-jinja2 0.6.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-meld 0.3.5 
atom-mermaid 3.2.1 
atom-monokai 0.10.9 
atom-special-char-highlighter 0.1.0 
autocomplete-ansible 0.1.15 
autocomplete-asciidoc 0.1.2 
autocomplete-bash-builtins 0.3.5 
autocomplete-html-entities 0.2.0 
autocomplete-modules 1.11.0 
autocomplete-project-paths 2.2.0 
autocomplete-python 1.10.5 
bang 2.4.0 
bootstrap-vue-snippets 0.4.0 
busy-signal 1.4.3 
character-table 0.4.3 
chmod 0.1.1 
city-lights-syntax 1.1.8 
color-picker 2.2.5 
context-git 0.20.0 
copy-as-rtf 0.9.3 
dash 1.7.1 
docblockr 0.13.6 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
easysort-yaml 0.4.1 
editorconfig 2.2.2 
emmet-simplified 2.5.0 
escape-utils 0.5.3 
file-icons 2.1.16 
file-templates 0.2.0 
file-types 0.5.5 
file-watcher 1.2.6 
flatwhite-syntax 0.8.1 
format-shell 2.0.0 
genesis-syntax 1.0.9 
git-blame 1.5.0 
git-hide 1.0.0 
git-time-machine 1.5.9 
hard-wrap 1.7.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
json-converter 0.2.4 
language-ansible 0.2.2 
language-asciidoc 1.11.0 
language-babel 2.84.0 
language-batch 0.4.0 
language-csv 1.1.2 
language-diff 0.7.0 
language-docker 1.1.8 
language-dotfiles 1.1.0 
language-dots 0.0.4 
language-generic-config 1.4.0 
language-gradle 0.0.5 
language-groovy 0.7.0 
language-hosts 0.1.2 
language-ini 1.19.0 
language-latex 1.1.1 
language-log 1.9.0 
language-mermaid 0.6.0 
language-mongodb 0.3.1 
language-nginx 0.8.0 
language-pgsql 0.2.3 
language-powershell 4.0.0 
language-pug 0.0.22 
language-restructuredtext 1.1.0 
language-robot-framework 2.2.0 
language-stylus 0.2.0 
language-svg 0.9.2 
language-vue 0.23.1 
last-cursor-position 0.9.2 
less-than-slash 0.18.0 
linter 2.2.0 
linter-alex 4.0.0 
linter-ansible-linting 1.3.1 
linter-ansible-syntax 1.2.0 
linter-csslint 2.0.0 
linter-docker 0.3.0 
linter-eslint 8.4.1 
linter-js-standard 4.2.0 
linter-js-yaml 1.2.8 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-markdown 5.2.0 
linter-proselint 3.3.0 
linter-pug 2.0.3 
linter-pycodestyle 2.1.3 
linter-pydocstyle 0.4.7 
linter-ruby 1.2.6 
linter-sass-lint 1.8.3 
linter-shellcheck 1.4.6 
linter-swagger 0.4.2 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
linter-xmllint 1.4.3 
MagicPython 1.0.12 
markdown-preview-enhanced 0.15.2 
markdown-preview-plus 2.5.3 
markdown-writer 2.7.3 
material-palenight-syntax 1.5.7 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
monokai 0.24.0 
monokai-slate 0.6.0 
nebula-syntax 0.4.5 
nebula-ui 0.9.2 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
oceanic-next 1.0.0 
oceanic-reef-syntax 0.9.0 
open-terminal-here 2.3.1 
prettier-atom 0.51.0 
pretty-json 1.6.4 
pristine-ui 1.1.11 
pubster-syntax 3.0.2 
pure-syntax 0.3.0 
quick-query 0.12.2 
regex-railroad-diagram 0.19.4 
robot-selenium-snippet 1.0.1 
rst-preview-pandoc 0.1.12 
scroll-sync 0.2.4 
set-syntax 0.4.0 
slime 2.4.0 
sort-lines 0.18.0 
split-diff 1.5.2 
ssh-config 0.13.0 
standardjs-snippets 2.6.2 
Sublime-Style-Column-Selection 1.7.4 
susave 0.4.0 
symbols-tree-view 0.14.0 
synced-sidebar 0.4.3 
tablr 1.8.3 
tabs-closer 0.16.0 
text-manipulation 0.6.0 
title-case 0.4.0 
toggle-quotes 1.1.0 
tornado-templates 0.2.0 
tree-view-git-status 1.4.0 
tree-view-scope-lines 0.2.0 
url-open 0.1.0 
vue2-autocomplete 0.1.0-alpha.4 
Zen 0.18.0 
```

**Comment by bennypowers** [comment]
This only happens to me when Tree Sitter Parsers are activated
