### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenIndexAtBufferColumn' of undefined

### ISSUE THREAD

**Issue by ilanbiala** [klorenz/atom-regex-railroad-diagrams#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.9.5
**Thrown From**: [regex-railroad-diagram](https://github.com/klorenz/atom-regex-railroad-diagrams) package, v0.6.3

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenIndexAtBufferColumn' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:567

TypeError: Cannot read property 'tokenIndexAtBufferColumn' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.bufferRangeForScopeAtPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:567:33)
  at DisplayBuffer.module.exports.DisplayBuffer.bufferRangeForScopeAtPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/display-buffer.js:1048:35)
  at TextEditor.module.exports.TextEditor.bufferRangeForScopeAtCursor (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor.js:2441:33)
  at RegexRailroadDiagramView.module.exports.RegexRailroadDiagramView.updateRailRoadDiagram (/Users/Ilan/.atom/packages/regex-railroad-diagram/lib/regex-railroad-diagram-view.coffee:26:20)
  at atom-workspace.<anonymous> (/Users/Ilan/.atom/packages/regex-railroad-diagram/lib/regex-railroad-diagram-view.coffee:1:1)
  at atom-workspace.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:198:49)
  at CallbackQueue.mixInto.notifyAll (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-component.js:243:28

```

### Commands

```
     -9:39.9 core:save (atom-text-editor.editor.is-focused)
  2x -9:37.4 core:cut (atom-text-editor.editor.is-focused)
     -9:36.9 core:save (atom-text-editor.editor.is-focused)
     -9:11.3 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -9:10.8 core:save (atom-text-editor.editor.is-focused)
     -6:44.6 core:cut (atom-text-editor.editor.is-focused)
     -6:44.3 core:save (atom-text-editor.editor.is-focused)
     -6:41.5 core:undo (atom-text-editor.editor.is-focused)
  2x -6:41.3 core:save (atom-text-editor.editor.is-focused)
     -6:23.4 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:21.4 core:move-down (atom-text-editor.editor.mini)
     -6:21.1 core:confirm (atom-text-editor.editor.mini)
     -6:21.1 editor:auto-indent (atom-text-editor.editor.is-focused)
  3x -6:19.4 core:save (atom-text-editor.editor.is-focused)
  7x -0:05.0 core:undo (atom-text-editor.editor.is-focused)
     -0:00.6 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
docblockr, v0.5.8
editorconfig, v0.3.0
emmet, v2.3.3
git-log, v0.2.0
jsformat, v0.7.18
language-jade, v0.3.0
language-json, v0.12.0
linter, v0.11.1
linter-jshint, v0.1.0
regex-railroad-diagram, v0.6.3
seti-syntax, v0.3.1
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by klorenz** [comment]
Hi Ilanbiala, I suppose this is not an issue anymore, so I close it. Regards, Kiwi
