### ISSUE TITLE
Cannot find module 'regexp'

### ISSUE THREAD

**Issue by ottnorml** [klorenz/atom-regex-railroad-diagrams#50]
Hey Guys,

I get this annoying error message. How can I fix this problem?
Where do I get the 'regexp' module?
Attached you find the steps I did so far and the atom report.

Best regards,
Ottnorml

======================================================================

1. Install atom-regex-railroad-diagrams packet over atom build-in package finder/installer
2. Restart atom

**Atom Version**: 1.0.0
**System**: ADMIN-PC
**Thrown From**: [atom-regex-railroad-diagrams](https://github.com/klorenz/atom-regex-railroad-diagrams) package, vundefined

### Stack Trace

Failed to load the regex-railroad-diagram package

```
At Cannot find module 'regexp'

Error: Cannot find module 'regexp'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\OttNorml\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/OttNorml/.atom/packages/atom-regex-railroad-diagrams/lib/regex-to-railroad.coffee:4:11)
    at Object.<anonymous> (/C:/Users/OttNorml/.atom/packages/atom-regex-railroad-diagrams/lib/regex-to-railroad.coffee:224:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\OttNorml\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.9
minimap, v4.10.2
pigments, v0.8.2
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by klorenz** [comment]
Hi ottnorml,
is this still an issue? I did some fixes in package.json some time ago.

Regards, Kiwi
